$services = @("AppVClient",
  "AxInstSV",
  "BcastDVRUserService",
  "BluetoothUserService",
  "bthserv",
  "CscService",
  "dmwappushservice",
  "FrameServer",
  "icssvc",
  "lfsvc",
  "lltdsvc",
  "MapsBroker",
  "NetTcpPortSharing",
  "OneSyncSvc",
  "PhoneSvc",
  "PimIndexMaintenanceSvc",
  "QWAVE",
  "RemoteAccess",
  "SCardSvr",
  "ScDeviceEnum",
  "SensorDataService",
  "SensorService",
  "SensrSvc",
  "SharedAccess",
  "ShellHWDetection",
  "SSDPSRV",
  "TabletInputService",
  "UevAgentService",
  "upnphost",
  "UserDataSvc",
  "WalletService",
  "WiaRpc",
  "wisvc",
  "WSearch",
  "XblAuthManager",
  "XblGameSave")

foreach ($service in $services) {
  Write-Output "Disabling $service"
  Get-Service $service -ErrorAction SilentlyContinue | Stop-Service -PassThru -ErrorAction SilentlyContinue | Set-Service -StartupType Disabled
}
